"""
echo_ssh - App Market
A modern panel that lists software packages suitable for the detected remote
system. Each package has a card with name, description, category and an
Install button that runs the appropriate package manager command.
"""

from PyQt6.QtCore import Qt, pyqtSignal
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QScrollArea,
    QFrame, QComboBox, QGridLayout
)

from i18n import tr
from system_info import SystemInfo, install_command


# Package definitions. Each entry: key, name_en, name_zh, category, desc_en, desc_zh, pkgs (dict pm->pkg name)
CATEGORIES = ["all", "dev", "web", "database", "system", "network", "media", "security"]

PACKAGES = [{'key': 'git',
  'cat': 'dev',
  'icon': '📦',
  'name_en': 'Git',
  'name_zh': 'Git 版本控制',
  'desc_en': 'Distributed version control system',
  'desc_zh': '分布式版本控制系统',
  'pkgs': {'apt': 'git', 'dnf': 'git', 'yum': 'git', 'pacman': 'git', 'zypper': 'git', 'apk': 'git'}},
 {'key': 'vim',
  'cat': 'dev',
  'icon': '📝',
  'name_en': 'Vim',
  'name_zh': 'Vim 编辑器',
  'desc_en': 'Highly configurable text editor',
  'desc_zh': '高度可配置的文本编辑器',
  'pkgs': {'apt': 'vim', 'dnf': 'vim-enhanced', 'yum': 'vim-enhanced', 'pacman': 'vim', 'zypper': 'vim', 'apk': 'vim'}},
 {'key': 'gcc',
  'cat': 'dev',
  'icon': '⚙️',
  'name_en': 'GCC (build-essential)',
  'name_zh': 'GCC 编译工具链',
  'desc_en': 'C/C++ compiler and build tools',
  'desc_zh': 'C/C++ 编译器及构建工具',
  'pkgs': {'apt': 'build-essential',
           'dnf': 'gcc gcc-c++ make',
           'yum': 'gcc gcc-c++ make',
           'pacman': 'base-devel',
           'zypper': 'gcc gcc-c++ make',
           'apk': 'build-base'}},
 {'key': 'python3',
  'cat': 'dev',
  'icon': '🐍',
  'name_en': 'Python 3',
  'name_zh': 'Python 3',
  'desc_en': 'Python 3 interpreter and pip',
  'desc_zh': 'Python 3 解释器及 pip',
  'pkgs': {'apt': 'python3 python3-pip',
           'dnf': 'python3 python3-pip',
           'yum': 'python3 python3-pip',
           'pacman': 'python python-pip',
           'zypper': 'python3 python3-pip',
           'apk': 'python3 py3-pip'}},
 {'key': 'nodejs',
  'cat': 'dev',
  'icon': '🟢',
  'name_en': 'Node.js & npm',
  'name_zh': 'Node.js 与 npm',
  'desc_en': 'JavaScript runtime and package manager',
  'desc_zh': 'JavaScript 运行时与包管理器',
  'pkgs': {'apt': 'nodejs npm',
           'dnf': 'nodejs npm',
           'yum': 'nodejs npm',
           'pacman': 'nodejs npm',
           'zypper': 'nodejs npm',
           'apk': 'nodejs npm'}},
 {'key': 'docker',
  'cat': 'dev',
  'icon': '🐳',
  'name_en': 'Docker',
  'name_zh': 'Docker 容器',
  'desc_en': 'Container platform (uses official install script)',
  'desc_zh': '容器平台（使用官方安装脚本）',
  'pkgs': {'apt': '__docker__',
           'dnf': '__docker__',
           'yum': '__docker__',
           'pacman': 'docker',
           'zypper': 'docker',
           'apk': 'docker'},
  'custom': {'apt': 'curl -fsSL https://get.docker.com | sudo sh',
             'dnf': 'curl -fsSL https://get.docker.com | sudo sh',
             'yum': 'curl -fsSL https://get.docker.com | sudo sh',
             'pacman': 'sudo pacman -Sy --noconfirm docker',
             'zypper': 'sudo zypper --non-interactive install docker',
             'apk': 'sudo apk add docker'}},
 {'key': 'nginx',
  'cat': 'web',
  'icon': '🌐',
  'name_en': 'Nginx',
  'name_zh': 'Nginx 网页服务器',
  'desc_en': 'High-performance HTTP and reverse proxy server',
  'desc_zh': '高性能 HTTP 与反向代理服务器',
  'pkgs': {'apt': 'nginx', 'dnf': 'nginx', 'yum': 'nginx', 'pacman': 'nginx', 'zypper': 'nginx', 'apk': 'nginx'}},
 {'key': 'apache2',
  'cat': 'web',
  'icon': '🪶',
  'name_en': 'Apache HTTP Server',
  'name_zh': 'Apache 网页服务器',
  'desc_en': 'Classic open-source HTTP server',
  'desc_zh': '经典开源 HTTP 服务器',
  'pkgs': {'apt': 'apache2',
           'dnf': 'httpd',
           'yum': 'httpd',
           'pacman': 'apache',
           'zypper': 'apache2',
           'apk': 'apache2'}},
 {'key': 'caddy',
  'cat': 'web',
  'icon': '🚀',
  'name_en': 'Caddy',
  'name_zh': 'Caddy 网页服务器',
  'desc_en': 'Automatic HTTPS web server',
  'desc_zh': '自动 HTTPS 网页服务器',
  'pkgs': {'apt': 'caddy', 'dnf': 'caddy', 'yum': 'caddy', 'pacman': 'caddy', 'zypper': 'caddy', 'apk': 'caddy'}},
 {'key': 'mysql',
  'cat': 'database',
  'icon': '🐬',
  'name_en': 'MySQL / MariaDB',
  'name_zh': 'MySQL / MariaDB 数据库',
  'desc_en': 'Popular relational database server',
  'desc_zh': '流行的关系型数据库服务器',
  'pkgs': {'apt': 'mysql-server',
           'dnf': 'mariadb-server',
           'yum': 'mariadb-server',
           'pacman': 'mariadb',
           'zypper': 'mariadb',
           'apk': 'mariadb'}},
 {'key': 'postgresql',
  'cat': 'database',
  'icon': '🐘',
  'name_en': 'PostgreSQL',
  'name_zh': 'PostgreSQL 数据库',
  'desc_en': 'Advanced open-source relational database',
  'desc_zh': '功能强大的开源关系型数据库',
  'pkgs': {'apt': 'postgresql',
           'dnf': 'postgresql-server',
           'yum': 'postgresql-server',
           'pacman': 'postgresql',
           'zypper': 'postgresql',
           'apk': 'postgresql'}},
 {'key': 'redis',
  'cat': 'database',
  'icon': '🔴',
  'name_en': 'Redis',
  'name_zh': 'Redis 缓存',
  'desc_en': 'In-memory data structure store',
  'desc_zh': '内存数据结构存储',
  'pkgs': {'apt': 'redis-server',
           'dnf': 'redis',
           'yum': 'redis',
           'pacman': 'redis',
           'zypper': 'redis',
           'apk': 'redis'}},
 {'key': 'mongodb',
  'cat': 'database',
  'icon': '🍃',
  'name_en': 'MongoDB',
  'name_zh': 'MongoDB 文档数据库',
  'desc_en': 'NoSQL document database',
  'desc_zh': 'NoSQL 文档数据库',
  'pkgs': {'apt': 'mongodb',
           'dnf': 'mongodb',
           'yum': 'mongodb',
           'pacman': 'mongodb',
           'zypper': 'mongodb',
           'apk': 'mongodb'}},
 {'key': 'htop',
  'cat': 'system',
  'icon': '📊',
  'name_en': 'htop',
  'name_zh': 'htop 进程监控',
  'desc_en': 'Interactive process viewer',
  'desc_zh': '交互式进程查看器',
  'pkgs': {'apt': 'htop', 'dnf': 'htop', 'yum': 'htop', 'pacman': 'htop', 'zypper': 'htop', 'apk': 'htop'}},
 {'key': 'neofetch',
  'cat': 'system',
  'icon': '🎨',
  'name_en': 'neofetch',
  'name_zh': 'neofetch 系统信息',
  'desc_en': 'Display system information with style',
  'desc_zh': '美观地显示系统信息',
  'pkgs': {'apt': 'neofetch',
           'dnf': 'neofetch',
           'yum': 'neofetch',
           'pacman': 'neofetch',
           'zypper': 'neofetch',
           'apk': 'neofetch'}},
 {'key': 'tmux',
  'cat': 'system',
  'icon': '🔗',
  'name_en': 'tmux',
  'name_zh': 'tmux 终端复用',
  'desc_en': 'Terminal multiplexer',
  'desc_zh': '终端复用器',
  'pkgs': {'apt': 'tmux', 'dnf': 'tmux', 'yum': 'tmux', 'pacman': 'tmux', 'zypper': 'tmux', 'apk': 'tmux'}},
 {'key': 'htop_2',
  'cat': 'system',
  'icon': '💾',
  'name_en': 'sysstat',
  'name_zh': 'sysstat 性能工具',
  'desc_en': 'System performance monitoring tools (iostat, sar)',
  'desc_zh': '系统性能监控工具（iostat、sar）',
  'pkgs': {'apt': 'sysstat',
           'dnf': 'sysstat',
           'yum': 'sysstat',
           'pacman': 'sysstat',
           'zypper': 'sysstat',
           'apk': 'sysstat'}},
 {'key': 'curl',
  'cat': 'network',
  'icon': '🌊',
  'name_en': 'curl',
  'name_zh': 'curl 网络工具',
  'desc_en': 'Command-line tool for transferring data',
  'desc_zh': '命令行数据传输工具',
  'pkgs': {'apt': 'curl', 'dnf': 'curl', 'yum': 'curl', 'pacman': 'curl', 'zypper': 'curl', 'apk': 'curl'}},
 {'key': 'wget',
  'cat': 'network',
  'icon': '⬇️',
  'name_en': 'wget',
  'name_zh': 'wget 下载工具',
  'desc_en': 'Non-interactive network downloader',
  'desc_zh': '非交互式网络下载器',
  'pkgs': {'apt': 'wget', 'dnf': 'wget', 'yum': 'wget', 'pacman': 'wget', 'zypper': 'wget', 'apk': 'wget'}},
 {'key': 'nettools',
  'cat': 'network',
  'icon': '🕸️',
  'name_en': 'net-tools',
  'name_zh': 'net-tools 网络工具',
  'desc_en': 'Networking utilities (ifconfig, netstat)',
  'desc_zh': '网络工具集（ifconfig、netstat）',
  'pkgs': {'apt': 'net-tools',
           'dnf': 'net-tools',
           'yum': 'net-tools',
           'pacman': 'net-tools',
           'zypper': 'net-tools',
           'apk': 'net-tools'}},
 {'key': 'nmap',
  'cat': 'network',
  'icon': '🔍',
  'name_en': 'Nmap',
  'name_zh': 'Nmap 网络扫描',
  'desc_en': 'Network exploration and security scanner',
  'desc_zh': '网络探测与安全扫描器',
  'pkgs': {'apt': 'nmap', 'dnf': 'nmap', 'yum': 'nmap', 'pacman': 'nmap', 'zypper': 'nmap', 'apk': 'nmap'}},
 {'key': 'fail2ban',
  'cat': 'security',
  'icon': '🛡️',
  'name_en': 'Fail2ban',
  'name_zh': 'Fail2ban 防暴力破解',
  'desc_en': 'Ban IPs that fail authentication repeatedly',
  'desc_zh': '封禁反复认证失败的 IP',
  'pkgs': {'apt': 'fail2ban',
           'dnf': 'fail2ban',
           'yum': 'fail2ban',
           'pacman': 'fail2ban',
           'zypper': 'fail2ban',
           'apk': 'fail2ban'}},
 {'key': 'ufw',
  'cat': 'security',
  'icon': '🔥',
  'name_en': 'UFW Firewall',
  'name_zh': 'UFW 防火墙',
  'desc_en': 'Uncomplicated Firewall (Debian/Ubuntu)',
  'desc_zh': '简易防火墙（Debian/Ubuntu）',
  'pkgs': {'apt': 'ufw', 'dnf': 'ufw', 'yum': 'ufw', 'pacman': 'ufw', 'zypper': 'ufw', 'apk': 'ufw'}},
 {'key': 'ffmpeg',
  'cat': 'media',
  'icon': '🎬',
  'name_en': 'FFmpeg',
  'name_zh': 'FFmpeg 多媒体处理',
  'desc_en': 'Audio/video recording and conversion',
  'desc_zh': '音视频录制与转换',
  'pkgs': {'apt': 'ffmpeg', 'dnf': 'ffmpeg', 'yum': 'ffmpeg', 'pacman': 'ffmpeg', 'zypper': 'ffmpeg', 'apk': 'ffmpeg'}},
 {'key': 'golang',
  'cat': 'dev',
  'icon': '🐹',
  'name_en': 'Go',
  'name_zh': 'Go 语言',
  'desc_en': 'Fast, compiled statically typed language',
  'desc_zh': '快速静态编译语言',
  'pkgs': {'apt': 'golang-go', 'dnf': 'golang', 'yum': 'golang', 'pacman': 'go', 'zypper': 'golang', 'apk': 'go'}},
 {'key': 'rust',
  'cat': 'dev',
  'icon': '🦀',
  'name_en': 'Rust',
  'name_zh': 'Rust 语言',
  'desc_en': 'Systems programming language with memory safety',
  'desc_zh': '内存安全的系统级语言',
  'pkgs': {'apt': 'rustc cargo',
           'dnf': 'rust cargo',
           'yum': 'rust cargo',
           'pacman': 'rust cargo',
           'zypper': 'rust cargo',
           'apk': 'rust cargo'}},
 {'key': 'java_jdk',
  'cat': 'dev',
  'icon': '☕',
  'name_en': 'OpenJDK',
  'name_zh': 'OpenJDK Java',
  'desc_en': 'Java SE development kit',
  'desc_zh': 'Java SE 开发工具包',
  'pkgs': {'apt': 'openjdk-17-jdk',
           'dnf': 'java-17-openjdk-devel',
           'yum': 'java-17-openjdk-devel',
           'pacman': 'jre-openjdk jdk-openjdk',
           'zypper': 'java-17-openjdk-devel',
           'apk': 'openjdk17-jdk'}},
 {'key': 'maven',
  'cat': 'dev',
  'icon': '🏗',
  'name_en': 'Maven',
  'name_zh': 'Maven 构建工具',
  'desc_en': 'Apache Maven project builder',
  'desc_zh': 'Apache Maven 构建工具',
  'pkgs': {'apt': 'maven', 'dnf': 'maven', 'yum': 'maven', 'pacman': 'maven', 'zypper': 'maven', 'apk': 'maven'}},
 {'key': 'gradle',
  'cat': 'dev',
  'icon': '⚡',
  'name_en': 'Gradle',
  'name_zh': 'Gradle 构建工具',
  'desc_en': 'Fast build automation tool',
  'desc_zh': '快速构建自动化工具',
  'pkgs': {'apt': 'gradle', 'dnf': 'gradle', 'yum': 'gradle', 'pacman': 'gradle', 'zypper': 'gradle', 'apk': 'gradle'}},
 {'key': 'cmake',
  'cat': 'dev',
  'icon': '🧰',
  'name_en': 'CMake',
  'name_zh': 'CMake 构建系统',
  'desc_en': 'Cross-platform build system generator',
  'desc_zh': '跨平台构建系统生成器',
  'pkgs': {'apt': 'cmake', 'dnf': 'cmake', 'yum': 'cmake', 'pacman': 'cmake', 'zypper': 'cmake', 'apk': 'cmake'}},
 {'key': 'ninja',
  'cat': 'dev',
  'icon': '🥷',
  'name_en': 'Ninja Build',
  'name_zh': 'Ninja 构建工具',
  'desc_en': 'Small build system',
  'desc_zh': '轻量快速构建工具',
  'pkgs': {'apt': 'ninja-build',
           'dnf': 'ninja-build',
           'yum': 'ninja-build',
           'pacman': 'ninja',
           'zypper': 'ninja',
           'apk': 'ninja'}},
 {'key': 'php',
  'cat': 'dev',
  'icon': '🐘',
  'name_en': 'PHP 8',
  'name_zh': 'PHP 8',
  'desc_en': 'Popular server-side scripting language',
  'desc_zh': '流行的服务端脚本语言',
  'pkgs': {'apt': 'php-cli php-fpm',
           'dnf': 'php-cli php-fpm',
           'yum': 'php-cli php-fpm',
           'pacman': 'php',
           'zypper': 'php-fpm',
           'apk': 'php'}},
 {'key': 'composer',
  'cat': 'dev',
  'icon': '🎶',
  'name_en': 'Composer',
  'name_zh': 'Composer PHP 包管理',
  'desc_en': 'Dependency manager for PHP',
  'desc_zh': 'PHP 依赖管理工具',
  'pkgs': {'apt': 'composer',
           'dnf': 'composer',
           'yum': 'composer',
           'pacman': 'composer',
           'zypper': 'composer',
           'apk': 'composer'}},
 {'key': 'dotnet',
  'cat': 'dev',
  'icon': '🟣',
  'name_en': '.NET SDK',
  'name_zh': '.NET SDK',
  'desc_en': 'Microsoft .NET development platform',
  'desc_zh': '微软 .NET 开发平台',
  'pkgs': {'apt': 'dotnet-sdk-8.0',
           'dnf': 'dotnet-sdk-8.0',
           'yum': 'dotnet-sdk-8.0',
           'pacman': 'dotnet-sdk',
           'zypper': 'dotnet-sdk-8.0',
           'apk': 'dotnet-sdk'}},
 {'key': 'perl',
  'cat': 'dev',
  'icon': '🦪',
  'name_en': 'Perl',
  'name_zh': 'Perl 脚本语言',
  'desc_en': 'Feature-rich scripting language',
  'desc_zh': '功能丰富的脚本语言',
  'pkgs': {'apt': 'perl', 'dnf': 'perl', 'yum': 'perl', 'pacman': 'perl', 'zypper': 'perl', 'apk': 'perl'}},
 {'key': 'lua',
  'cat': 'dev',
  'icon': '🌙',
  'name_en': 'Lua',
  'name_zh': 'Lua 语言',
  'desc_en': 'Lightweight embeddable scripting',
  'desc_zh': '轻量可嵌入脚本语言',
  'pkgs': {'apt': 'lua5.4', 'dnf': 'lua', 'yum': 'lua', 'pacman': 'lua', 'zypper': 'lua', 'apk': 'lua5.4'}},
 {'key': 'sqlite',
  'cat': 'dev',
  'icon': '🗄',
  'name_en': 'SQLite',
  'name_zh': 'SQLite 数据库',
  'desc_en': 'Embedded zero-config SQL database',
  'desc_zh': '零配置嵌入式 SQL 数据库',
  'pkgs': {'apt': 'sqlite3',
           'dnf': 'sqlite',
           'yum': 'sqlite',
           'pacman': 'sqlite',
           'zypper': 'sqlite',
           'apk': 'sqlite'}},
 {'key': 'jq',
  'cat': 'dev',
  'icon': '🧩',
  'name_en': 'jq',
  'name_zh': 'jq JSON 处理',
  'desc_en': 'Command-line JSON processor',
  'desc_zh': '命令行 JSON 处理器',
  'pkgs': {'apt': 'jq', 'dnf': 'jq', 'yum': 'jq', 'pacman': 'jq', 'zypper': 'jq', 'apk': 'jq'}},
 {'key': 'shellcheck',
  'cat': 'dev',
  'icon': '🐚',
  'name_en': 'shellcheck',
  'name_zh': 'Shell 脚本检查器',
  'desc_en': 'Static analysis for shell scripts',
  'desc_zh': 'Shell 脚本静态分析工具',
  'pkgs': {'apt': 'shellcheck',
           'dnf': 'shellcheck',
           'yum': 'shellcheck',
           'pacman': 'shellcheck',
           'zypper': 'shellcheck',
           'apk': 'shellcheck'}},
 {'key': 'gdb',
  'cat': 'dev',
  'icon': '🐛',
  'name_en': 'GDB',
  'name_zh': 'GDB 调试器',
  'desc_en': 'GNU debugger',
  'desc_zh': 'GNU 调试器',
  'pkgs': {'apt': 'gdb', 'dnf': 'gdb', 'yum': 'gdb', 'pacman': 'gdb', 'zypper': 'gdb', 'apk': 'gdb'}},
 {'key': 'openresty',
  'cat': 'web',
  'icon': '🟨',
  'name_en': 'OpenResty',
  'name_zh': 'OpenResty',
  'desc_en': 'Nginx + LuaJIT web platform',
  'desc_zh': 'Nginx + LuaJIT 增强版',
  'pkgs': {'apt': 'openresty',
           'dnf': 'openresty',
           'yum': 'openresty',
           'pacman': 'openresty',
           'zypper': 'openresty',
           'apk': 'openresty'}},
 {'key': 'traefik',
  'cat': 'web',
  'icon': '🧭',
  'name_en': 'Traefik',
  'name_zh': 'Traefik 反向代理',
  'desc_en': 'Cloud-native edge router',
  'desc_zh': '云原生边缘路由器',
  'pkgs': {'apt': 'traefik',
           'dnf': 'traefik',
           'yum': 'traefik',
           'pacman': 'traefik',
           'zypper': 'traefik',
           'apk': 'traefik'}},
 {'key': 'haproxy',
  'cat': 'web',
  'icon': '⚖',
  'name_en': 'HAProxy',
  'name_zh': 'HAProxy 负载均衡',
  'desc_en': 'High-performance load balancer',
  'desc_zh': '高性能负载均衡器',
  'pkgs': {'apt': 'haproxy',
           'dnf': 'haproxy',
           'yum': 'haproxy',
           'pacman': 'haproxy',
           'zypper': 'haproxy',
           'apk': 'haproxy'}},
 {'key': 'varnish',
  'cat': 'web',
  'icon': '💴',
  'name_en': 'Varnish',
  'name_zh': 'Varnish 缓存',
  'desc_en': 'HTTP reverse proxy cache',
  'desc_zh': 'HTTP 反向代理缓存',
  'pkgs': {'apt': 'varnish',
           'dnf': 'varnish',
           'yum': 'varnish',
           'pacman': 'varnish',
           'zypper': 'varnish',
           'apk': 'varnish'}},
 {'key': 'gitea',
  'cat': 'web',
  'icon': '🍵',
  'name_en': 'Gitea',
  'name_zh': 'Gitea Git 托管',
  'desc_en': 'Lightweight self-hosted Git service',
  'desc_zh': '轻量自托管 Git 服务',
  'pkgs': {'apt': 'gitea', 'dnf': 'gitea', 'yum': 'gitea', 'pacman': 'gitea', 'zypper': 'gitea', 'apk': 'gitea'}},
 {'key': 'nextcloud',
  'cat': 'web',
  'icon': '☁',
  'name_en': 'Nextcloud',
  'name_zh': 'Nextcloud 云盘',
  'desc_en': 'Self-hosted productivity cloud',
  'desc_zh': '自托管生产力云平台',
  'pkgs': {'apt': 'nextcloud-server',
           'dnf': 'nextcloud',
           'yum': 'nextcloud',
           'pacman': 'nextcloud',
           'zypper': 'nextcloud',
           'apk': 'nextcloud'}},
 {'key': 'jellyfin',
  'cat': 'web',
  'icon': '🎬',
  'name_en': 'Jellyfin',
  'name_zh': 'Jellyfin 媒体服务器',
  'desc_en': 'Free software media system',
  'desc_zh': '开源媒体中心服务器',
  'pkgs': {'apt': 'jellyfin',
           'dnf': 'jellyfin',
           'yum': 'jellyfin',
           'pacman': 'jellyfin',
           'zypper': 'jellyfin',
           'apk': 'jellyfin'}},
 {'key': 'portainer',
  'cat': 'web',
  'icon': '🐳',
  'name_en': 'Portainer',
  'name_zh': 'Portainer 容器管理',
  'desc_en': 'Web UI for Docker/Kubernetes',
  'desc_zh': 'Docker/Kubernetes Web 管理界面',
  'pkgs': {'apt': 'portainer',
           'dnf': 'portainer',
           'yum': 'portainer',
           'pacman': 'portainer',
           'zypper': 'portainer',
           'apk': 'portainer'}},
 {'key': 'cassandra',
  'cat': 'database',
  'icon': '🪸',
  'name_en': 'Cassandra',
  'name_zh': 'Cassandra 分布式数据库',
  'desc_en': 'Highly scalable distributed DB',
  'desc_zh': '高可扩展分布式数据库',
  'pkgs': {'apt': 'cassandra',
           'dnf': 'cassandra',
           'yum': 'cassandra',
           'pacman': 'cassandra',
           'zypper': 'cassandra',
           'apk': 'cassandra'}},
 {'key': 'elasticsearch',
  'cat': 'database',
  'icon': '🔎',
  'name_en': 'Elasticsearch',
  'name_zh': 'Elasticsearch 搜索引擎',
  'desc_en': 'Distributed search and analytics',
  'desc_zh': '分布式搜索与分析引擎',
  'pkgs': {'apt': 'elasticsearch',
           'dnf': 'elasticsearch',
           'yum': 'elasticsearch',
           'pacman': 'elasticsearch',
           'zypper': 'elasticsearch',
           'apk': 'elasticsearch'}},
 {'key': 'mssql',
  'cat': 'database',
  'icon': '🟩',
  'name_en': 'SQL Server',
  'name_zh': 'SQL Server 数据库',
  'desc_en': 'Microsoft relational database',
  'desc_zh': '微软关系型数据库',
  'pkgs': {'apt': 'mssql-server',
           'dnf': 'mssql-server',
           'yum': 'mssql-server',
           'pacman': 'mssql-server',
           'zypper': 'mssql-server',
           'apk': 'mssql-server'}},
 {'key': 'influxdb',
  'cat': 'database',
  'icon': '📈',
  'name_en': 'InfluxDB',
  'name_zh': 'InfluxDB 时序数据库',
  'desc_en': 'Time-series database for metrics',
  'desc_zh': '指标时序数据库',
  'pkgs': {'apt': 'influxdb',
           'dnf': 'influxdb',
           'yum': 'influxdb',
           'pacman': 'influxdb',
           'zypper': 'influxdb',
           'apk': 'influxdb'}},
 {'key': 'clickhouse',
  'cat': 'database',
  'icon': '🖱',
  'name_en': 'ClickHouse',
  'name_zh': 'ClickHouse 列式数据库',
  'desc_en': 'Column-oriented analytics DB',
  'desc_zh': '列式分析型数据库',
  'pkgs': {'apt': 'clickhouse-server',
           'dnf': 'clickhouse-server',
           'yum': 'clickhouse-server',
           'pacman': 'clickhouse',
           'zypper': 'clickhouse-server',
           'apk': 'clickhouse-server'}},
 {'key': 'pgadmin',
  'cat': 'database',
  'icon': '🐘',
  'name_en': 'pgAdmin',
  'name_zh': 'pgAdmin 管理工具',
  'desc_en': 'PostgreSQL admin tool',
  'desc_zh': 'PostgreSQL 管理工具',
  'pkgs': {'apt': 'pgadmin4',
           'dnf': 'pgadmin4',
           'yum': 'pgadmin4',
           'pacman': 'pgadmin',
           'zypper': 'pgadmin4',
           'apk': 'pgadmin'}},
 {'key': 'etcd',
  'cat': 'database',
  'icon': '🔢',
  'name_en': 'etcd',
  'name_zh': 'etcd 分布式键值',
  'desc_en': 'Distributed key-value store',
  'desc_zh': '分布式键值存储',
  'pkgs': {'apt': 'etcd', 'dnf': 'etcd', 'yum': 'etcd', 'pacman': 'etcd', 'zypper': 'etcd', 'apk': 'etcd'}},
 {'key': 'btop',
  'cat': 'system',
  'icon': '📈',
  'name_en': 'btop',
  'name_zh': 'btop 资源监控',
  'desc_en': 'Resource monitor in TTY',
  'desc_zh': 'TTY 资源监控器',
  'pkgs': {'apt': 'btop', 'dnf': 'btop', 'yum': 'btop', 'pacman': 'btop', 'zypper': 'btop', 'apk': 'btop'}},
 {'key': 'ncdu',
  'cat': 'system',
  'icon': '💽',
  'name_en': 'ncdu',
  'name_zh': 'ncdu 磁盘分析',
  'desc_en': 'Disk usage analyzer',
  'desc_zh': '磁盘使用分析器',
  'pkgs': {'apt': 'ncdu', 'dnf': 'ncdu', 'yum': 'ncdu', 'pacman': 'ncdu', 'zypper': 'ncdu', 'apk': 'ncdu'}},
 {'key': 'tree',
  'cat': 'system',
  'icon': '🌲',
  'name_en': 'tree',
  'name_zh': 'tree 目录树',
  'desc_en': 'List directories as tree',
  'desc_zh': '树形列出目录结构',
  'pkgs': {'apt': 'tree', 'dnf': 'tree', 'yum': 'tree', 'pacman': 'tree', 'zypper': 'tree', 'apk': 'tree'}},
 {'key': 'iotop',
  'cat': 'system',
  'icon': '🔊',
  'name_en': 'iotop',
  'name_zh': 'iotop I/O 监控',
  'desc_en': 'I/O usage top',
  'desc_zh': 'I/O 使用量 top 工具',
  'pkgs': {'apt': 'iotop', 'dnf': 'iotop', 'yum': 'iotop', 'pacman': 'iotop', 'zypper': 'iotop', 'apk': 'iotop'}},
 {'key': 'iftop',
  'cat': 'system',
  'icon': '📡',
  'name_en': 'iftop',
  'name_zh': 'iftop 网络流量',
  'desc_en': 'Bandwidth usage by host',
  'desc_zh': '按主机显示带宽使用',
  'pkgs': {'apt': 'iftop', 'dnf': 'iftop', 'yum': 'iftop', 'pacman': 'iftop', 'zypper': 'iftop', 'apk': 'iftop'}},
 {'key': 'lsof',
  'cat': 'system',
  'icon': '🔒',
  'name_en': 'lsof',
  'name_zh': 'lsof 打开文件',
  'desc_en': 'List open files',
  'desc_zh': '列出已打开文件',
  'pkgs': {'apt': 'lsof', 'dnf': 'lsof', 'yum': 'lsof', 'pacman': 'lsof', 'zypper': 'lsof', 'apk': 'lsof'}},
 {'key': 'screen',
  'cat': 'system',
  'icon': '🖥',
  'name_en': 'GNU Screen',
  'name_zh': 'GNU Screen 终端复用',
  'desc_en': 'Alternative terminal multiplexer',
  'desc_zh': '替代终端复用器',
  'pkgs': {'apt': 'screen', 'dnf': 'screen', 'yum': 'screen', 'pacman': 'screen', 'zypper': 'screen', 'apk': 'screen'}},
 {'key': 'zsh',
  'cat': 'system',
  'icon': '🐚',
  'name_en': 'Zsh',
  'name_zh': 'Z shell',
  'desc_en': 'Powerful interactive shell',
  'desc_zh': '强大的交互式 Shell',
  'pkgs': {'apt': 'zsh', 'dnf': 'zsh', 'yum': 'zsh', 'pacman': 'zsh', 'zypper': 'zsh', 'apk': 'zsh'}},
 {'key': 'fish',
  'cat': 'system',
  'icon': '🐟',
  'name_en': 'Fish Shell',
  'name_zh': 'Fish Shell',
  'desc_en': 'Friendly interactive shell',
  'desc_zh': '友好的交互式 Shell',
  'pkgs': {'apt': 'fish', 'dnf': 'fish', 'yum': 'fish', 'pacman': 'fish', 'zypper': 'fish', 'apk': 'fish'}},
 {'key': 'rsync',
  'cat': 'system',
  'icon': '🔃',
  'name_en': 'rsync',
  'name_zh': 'rsync 同步',
  'desc_en': 'Fast file transfer tool',
  'desc_zh': '快速文件传输工具',
  'pkgs': {'apt': 'rsync', 'dnf': 'rsync', 'yum': 'rsync', 'pacman': 'rsync', 'zypper': 'rsync', 'apk': 'rsync'}},
 {'key': 'unzip',
  'cat': 'system',
  'icon': '🟨',
  'name_en': 'unzip',
  'name_zh': 'unzip 解压工具',
  'desc_en': 'Decompress ZIP archives',
  'desc_zh': '解压 ZIP 压缩包',
  'pkgs': {'apt': 'unzip', 'dnf': 'unzip', 'yum': 'unzip', 'pacman': 'unzip', 'zypper': 'unzip', 'apk': 'unzip'}},
 {'key': 'zip',
  'cat': 'system',
  'icon': '📦',
  'name_en': 'zip',
  'name_zh': 'zip 压缩工具',
  'desc_en': 'Create ZIP archives',
  'desc_zh': '创建 ZIP 压缩包',
  'pkgs': {'apt': 'zip', 'dnf': 'zip', 'yum': 'zip', 'pacman': 'zip', 'zypper': 'zip', 'apk': 'zip'}},
 {'key': 'p7zip',
  'cat': 'system',
  'icon': '📦',
  'name_en': 'p7zip',
  'name_zh': '7-Zip 解压缩',
  'desc_en': '7-Zip archiver (CLI)',
  'desc_zh': '7-Zip 命令行归档工具',
  'pkgs': {'apt': 'p7zip-full', 'dnf': 'p7zip', 'yum': 'p7zip', 'pacman': 'p7zip', 'zypper': 'p7zip', 'apk': 'p7zip'}},
 {'key': 'mtr',
  'cat': 'network',
  'icon': '🧭',
  'name_en': 'MTR',
  'name_zh': 'MTR 网络诊断',
  'desc_en': 'My traceroute + ping',
  'desc_zh': 'My traceroute 与 ping 组合',
  'pkgs': {'apt': 'mtr-tiny', 'dnf': 'mtr', 'yum': 'mtr', 'pacman': 'mtr', 'zypper': 'mtr', 'apk': 'mtr'}},
 {'key': 'bind',
  'cat': 'network',
  'icon': '🔗',
  'name_en': 'BIND DNS',
  'name_zh': 'BIND DNS 服务器',
  'desc_en': 'The standard DNS server',
  'desc_zh': '标准 DNS 服务器',
  'pkgs': {'apt': 'bind9', 'dnf': 'bind', 'yum': 'bind', 'pacman': 'bind', 'zypper': 'bind', 'apk': 'bind'}},
 {'key': 'dnsmasq',
  'cat': 'network',
  'icon': '🏠',
  'name_en': 'dnsmasq',
  'name_zh': 'dnsmasq 小型 DNS',
  'desc_en': 'Lightweight DNS/DHCP server',
  'desc_zh': '轻量 DNS/DHCP 服务器',
  'pkgs': {'apt': 'dnsmasq',
           'dnf': 'dnsmasq',
           'yum': 'dnsmasq',
           'pacman': 'dnsmasq',
           'zypper': 'dnsmasq',
           'apk': 'dnsmasq'}},
 {'key': 'tcpdump',
  'cat': 'network',
  'icon': '📥',
  'name_en': 'tcpdump',
  'name_zh': 'tcpdump 抓包',
  'desc_en': 'Packet capture tool',
  'desc_zh': '网络包捕获工具',
  'pkgs': {'apt': 'tcpdump',
           'dnf': 'tcpdump',
           'yum': 'tcpdump',
           'pacman': 'tcpdump',
           'zypper': 'tcpdump',
           'apk': 'tcpdump'}},
 {'key': 'wireshark',
  'cat': 'network',
  'icon': '🔍',
  'name_en': 'Wireshark',
  'name_zh': 'Wireshark 抓包分析',
  'desc_en': 'Network protocol analyzer',
  'desc_zh': '网络协议分析器',
  'pkgs': {'apt': 'wireshark',
           'dnf': 'wireshark',
           'yum': 'wireshark',
           'pacman': 'wireshark',
           'zypper': 'wireshark',
           'apk': 'wireshark'}},
 {'key': 'netcat',
  'cat': 'network',
  'icon': '🐱',
  'name_en': 'netcat',
  'name_zh': 'netcat 网络工具',
  'desc_en': 'Network TCP/UDP tool',
  'desc_zh': 'TCP/UDP 网络瑞士军刀',
  'pkgs': {'apt': 'netcat-openbsd',
           'dnf': 'nmap-ncat',
           'yum': 'nmap-ncat',
           'pacman': 'openbsd-netcat',
           'zypper': 'netcat-openbsd',
           'apk': 'netcat-openbsd'}},
 {'key': 'socat',
  'cat': 'network',
  'icon': '🔗',
  'name_en': 'socat',
  'name_zh': 'socat 套接字工具',
  'desc_en': 'Bidirectional relay',
  'desc_zh': '双向中继工具',
  'pkgs': {'apt': 'socat', 'dnf': 'socat', 'yum': 'socat', 'pacman': 'socat', 'zypper': 'socat', 'apk': 'socat'}},
 {'key': 'openvpn',
  'cat': 'network',
  'icon': '🔒',
  'name_en': 'OpenVPN',
  'name_zh': 'OpenVPN',
  'desc_en': 'SSL/TLS VPN',
  'desc_zh': 'SSL/TLS VPN 解决方案',
  'pkgs': {'apt': 'openvpn',
           'dnf': 'openvpn',
           'yum': 'openvpn',
           'pacman': 'openvpn',
           'zypper': 'openvpn',
           'apk': 'openvpn'}},
 {'key': 'wireguard',
  'cat': 'network',
  'icon': '🛡',
  'name_en': 'WireGuard',
  'name_zh': 'WireGuard',
  'desc_en': 'Fast modern VPN tunnel',
  'desc_zh': '快速现代 VPN 隧道',
  'pkgs': {'apt': 'wireguard',
           'dnf': 'wireguard-tools',
           'yum': 'wireguard-tools',
           'pacman': 'wireguard-tools',
           'zypper': 'wireguard-tools',
           'apk': 'wireguard-tools'}},
 {'key': 'tailscale',
  'cat': 'network',
  'icon': '🐭',
  'name_en': 'Tailscale',
  'name_zh': 'Tailscale 组网',
  'desc_en': 'Secure mesh VPN',
  'desc_zh': '安全 Mesh VPN',
  'pkgs': {'apt': 'tailscale',
           'dnf': 'tailscale',
           'yum': 'tailscale',
           'pacman': 'tailscale',
           'zypper': 'tailscale',
           'apk': 'tailscale'}},
 {'key': 'iperf',
  'cat': 'network',
  'icon': '📊',
  'name_en': 'iperf3',
  'name_zh': 'iperf3 带宽测试',
  'desc_en': 'Network throughput benchmark',
  'desc_zh': '网络吞吐性能测试',
  'pkgs': {'apt': 'iperf3', 'dnf': 'iperf3', 'yum': 'iperf3', 'pacman': 'iperf', 'zypper': 'iperf3', 'apk': 'iperf3'}},
 {'key': 'samba',
  'cat': 'network',
  'icon': '🍞',
  'name_en': 'Samba',
  'name_zh': 'Samba 文件共享',
  'desc_en': 'SMB file and print server',
  'desc_zh': 'SMB 文件和打印服务器',
  'pkgs': {'apt': 'samba', 'dnf': 'samba', 'yum': 'samba', 'pacman': 'samba', 'zypper': 'samba', 'apk': 'samba'}},
 {'key': 'nfs',
  'cat': 'network',
  'icon': '📂',
  'name_en': 'NFS',
  'name_zh': 'NFS 文件系统',
  'desc_en': 'Network File System (server)',
  'desc_zh': '网络文件系统',
  'pkgs': {'apt': 'nfs-kernel-server',
           'dnf': 'nfs-utils',
           'yum': 'nfs-utils',
           'pacman': 'nfs-utils',
           'zypper': 'nfs-kernel-server',
           'apk': 'nfs'}},
 {'key': 'ufw_fw',
  'cat': 'security',
  'icon': '🔥',
  'name_en': 'UFW Firewall',
  'name_zh': 'UFW 防火墙',
  'desc_en': 'Uncomplicated Firewall (Debian/Ubuntu)',
  'desc_zh': '简易防火墙（Debian/Ubuntu）',
  'pkgs': {'apt': 'ufw', 'dnf': 'ufw', 'yum': 'ufw', 'pacman': 'ufw', 'zypper': 'ufw', 'apk': 'ufw'}},
 {'key': 'firewalld',
  'cat': 'security',
  'icon': '🧱',
  'name_en': 'firewalld',
  'name_zh': 'firewalld 防火墙',
  'desc_en': 'Dynamic firewall manager',
  'desc_zh': '动态防火墙管理器',
  'pkgs': {'apt': 'firewalld',
           'dnf': 'firewalld',
           'yum': 'firewalld',
           'pacman': 'firewalld',
           'zypper': 'firewalld',
           'apk': 'firewalld'}},
 {'key': 'clamav',
  'cat': 'security',
  'icon': '🚪',
  'name_en': 'ClamAV',
  'name_zh': 'ClamAV 杀毒',
  'desc_en': 'Open-source antivirus engine',
  'desc_zh': '开源杀毒引擎',
  'pkgs': {'apt': 'clamav', 'dnf': 'clamav', 'yum': 'clamav', 'pacman': 'clamav', 'zypper': 'clamav', 'apk': 'clamav'}},
 {'key': 'rkhunter',
  'cat': 'security',
  'icon': '🕵',
  'name_en': 'rkhunter',
  'name_zh': 'rkhunter Rootkit 检测',
  'desc_en': 'Rootkit detector',
  'desc_zh': 'Rootkit 检测器',
  'pkgs': {'apt': 'rkhunter',
           'dnf': 'rkhunter',
           'yum': 'rkhunter',
           'pacman': 'rkhunter',
           'zypper': 'rkhunter',
           'apk': 'rkhunter'}},
 {'key': 'lynis',
  'cat': 'security',
  'icon': '🦊',
  'name_en': 'Lynis',
  'name_zh': 'Lynis 审计工具',
  'desc_en': 'Security auditing tool',
  'desc_zh': '安全审计工具',
  'pkgs': {'apt': 'lynis', 'dnf': 'lynis', 'yum': 'lynis', 'pacman': 'lynis', 'zypper': 'lynis', 'apk': 'lynis'}},
 {'key': 'auditd',
  'cat': 'security',
  'icon': '📋',
  'name_en': 'auditd',
  'name_zh': 'auditd 审计守护',
  'desc_en': 'Kernel audit daemon',
  'desc_zh': '内核审计守护进程',
  'pkgs': {'apt': 'auditd', 'dnf': 'audit', 'yum': 'audit', 'pacman': 'audit', 'zypper': 'audit', 'apk': 'audit'}},
 {'key': 'cryptsetup',
  'cat': 'security',
  'icon': '🔐',
  'name_en': 'cryptsetup',
  'name_zh': 'cryptsetup 磁盘加密',
  'desc_en': 'LUKS disk encryption utility',
  'desc_zh': 'LUKS 磁盘加密工具',
  'pkgs': {'apt': 'cryptsetup',
           'dnf': 'cryptsetup',
           'yum': 'cryptsetup',
           'pacman': 'cryptsetup',
           'zypper': 'cryptsetup',
           'apk': 'cryptsetup'}},
 {'key': 'ffmpeg_med',
  'cat': 'media',
  'icon': '🎬',
  'name_en': 'FFmpeg',
  'name_zh': 'FFmpeg 多媒体',
  'desc_en': 'Audio/video recording and conversion',
  'desc_zh': '音视频录制与转换',
  'pkgs': {'apt': 'ffmpeg', 'dnf': 'ffmpeg', 'yum': 'ffmpeg', 'pacman': 'ffmpeg', 'zypper': 'ffmpeg', 'apk': 'ffmpeg'}},
 {'key': 'yt_dlp',
  'cat': 'media',
  'icon': '📥',
  'name_en': 'yt-dlp',
  'name_zh': 'yt-dlp 视频下载',
  'desc_en': 'Video downloader fork',
  'desc_zh': '视频下载器增强版',
  'pkgs': {'apt': 'yt-dlp', 'dnf': 'yt-dlp', 'yum': 'yt-dlp', 'pacman': 'yt-dlp', 'zypper': 'yt-dlp', 'apk': 'yt-dlp'}},
 {'key': 'mpv',
  'cat': 'media',
  'icon': '🎵',
  'name_en': 'mpv',
  'name_zh': 'mpv 视频播放器',
  'desc_en': 'Minimalist video player',
  'desc_zh': '极简视频播放器',
  'pkgs': {'apt': 'mpv', 'dnf': 'mpv', 'yum': 'mpv', 'pacman': 'mpv', 'zypper': 'mpv', 'apk': 'mpv'}},
 {'key': 'vlc_cli',
  'cat': 'media',
  'icon': '🎞',
  'name_en': 'VLC',
  'name_zh': 'VLC 媒体播放器',
  'desc_en': 'Cross-platform media player',
  'desc_zh': '跨平台媒体播放器',
  'pkgs': {'apt': 'vlc', 'dnf': 'vlc', 'yum': 'vlc', 'pacman': 'vlc', 'zypper': 'vlc', 'apk': 'vlc'}},
 {'key': 'handbrake',
  'cat': 'media',
  'icon': '🤋',
  'name_en': 'HandBrake',
  'name_zh': 'HandBrake 视频转码',
  'desc_en': 'Video transcoder',
  'desc_zh': '视频转码工具',
  'pkgs': {'apt': 'handbrake-cli',
           'dnf': 'handbrake',
           'yum': 'handbrake',
           'pacman': 'handbrake',
           'zypper': 'handbrake',
           'apk': 'handbrake'}},
 {'key': 'imagemagick',
  'cat': 'media',
  'icon': '🖼',
  'name_en': 'ImageMagick',
  'name_zh': 'ImageMagick 图像处理',
  'desc_en': 'Image manipulation toolkit',
  'desc_zh': '图像处理工具包',
  'pkgs': {'apt': 'imagemagick',
           'dnf': 'ImageMagick',
           'yum': 'ImageMagick',
           'pacman': 'imagemagick',
           'zypper': 'ImageMagick',
           'apk': 'imagemagick'}},
 {'key': 'sox',
  'cat': 'media',
  'icon': '🔊',
  'name_en': 'SoX',
  'name_zh': 'SoX 音频处理',
  'desc_en': 'Audio Swiss army knife',
  'desc_zh': '音频瑞士军刀',
  'pkgs': {'apt': 'sox', 'dnf': 'sox', 'yum': 'sox', 'pacman': 'sox', 'zypper': 'sox', 'apk': 'sox'}},
 {'key': 'lame',
  'cat': 'media',
  'icon': '💿',
  'name_en': 'LAME',
  'name_zh': 'LAME MP3 编码器',
  'desc_en': 'High-quality MP3 encoder',
  'desc_zh': '高质量 MP3 编码器',
  'pkgs': {'apt': 'lame', 'dnf': 'lame', 'yum': 'lame', 'pacman': 'lame', 'zypper': 'lame', 'apk': 'lame'}},
 {'key': 'flac',
  'cat': 'media',
  'icon': '🎵',
  'name_en': 'FLAC',
  'name_zh': 'FLAC 无损音频',
  'desc_en': 'Free Lossless Audio Codec',
  'desc_zh': '自由无损音频编解码器',
  'pkgs': {'apt': 'flac', 'dnf': 'flac', 'yum': 'flac', 'pacman': 'flac', 'zypper': 'flac', 'apk': 'flac'}},
 {'key': 'opencv',
  'cat': 'media',
  'icon': '🤖',
  'name_en': 'OpenCV',
  'name_zh': 'OpenCV 计算机视觉',
  'desc_en': 'Computer vision library',
  'desc_zh': '计算机视觉库',
  'pkgs': {'apt': 'python3-opencv',
           'dnf': 'opencv-python',
           'yum': 'opencv-python',
           'pacman': 'opencv',
           'zypper': 'opencv',
           'apk': 'opencv'}},
 {'key': 'kvm',
  'cat': 'system',
  'icon': '🏠',
  'name_en': 'QEMU/KVM',
  'name_zh': 'QEMU/KVM 虚拟化',
  'desc_en': 'Full virtualization',
  'desc_zh': '全虚拟化技术',
  'pkgs': {'apt': 'qemu-kvm libvirt-daemon-system',
           'dnf': 'qemu-kvm libvirt',
           'yum': 'qemu-kvm libvirt',
           'pacman': 'qemu libvirt',
           'zypper': 'qemu libvirt',
           'apk': 'qemu libvirt'}},
 {'key': 'lxc',
  'cat': 'system',
  'icon': '📦',
  'name_en': 'LXC',
  'name_zh': 'LXC 容器',
  'desc_en': 'Linux containers',
  'desc_zh': '轻量 Linux 容器',
  'pkgs': {'apt': 'lxc lxd',
           'dnf': 'lxc lxd',
           'yum': 'lxc',
           'pacman': 'lxc lxd',
           'zypper': 'lxc lxd',
           'apk': 'lxc lxd'}},
 {'key': 'kubelet',
  'cat': 'system',
  'icon': '🐳',
  'name_en': 'Kubernetes',
  'name_zh': 'Kubernetes 编排',
  'desc_en': 'Container orchestration',
  'desc_zh': '容器编排平台',
  'pkgs': {'apt': 'kubelet kubeadm kubectl',
           'dnf': 'kubelet kubeadm kubectl',
           'yum': 'kubelet kubeadm kubectl',
           'pacman': 'kubectl',
           'zypper': 'kubelet kubeadm kubectl',
           'apk': 'kubectl'}},
 {'key': 'helm',
  'cat': 'system',
  'icon': '🪢',
  'name_en': 'Helm',
  'name_zh': 'Helm K8s 包管理',
  'desc_en': 'Kubernetes package manager',
  'desc_zh': 'Kubernetes 包管理器',
  'pkgs': {'apt': 'helm', 'dnf': 'helm', 'yum': 'helm', 'pacman': 'helm', 'zypper': 'helm', 'apk': 'helm'}},
 {'key': 'ansible',
  'cat': 'dev',
  'icon': '🤖',
  'name_en': 'Ansible',
  'name_zh': 'Ansible 自动化',
  'desc_en': 'Configuration automation',
  'desc_zh': '配置自动化工具',
  'pkgs': {'apt': 'ansible',
           'dnf': 'ansible-core',
           'yum': 'ansible-core',
           'pacman': 'ansible',
           'zypper': 'ansible',
           'apk': 'ansible'}},
 {'key': 'terraform',
  'cat': 'dev',
  'icon': '🌍',
  'name_en': 'Terraform',
  'name_zh': 'Terraform 基础设施',
  'desc_en': 'Infrastructure as code',
  'desc_zh': '基础设施即代码',
  'pkgs': {'apt': 'terraform',
           'dnf': 'terraform',
           'yum': 'terraform',
           'pacman': 'terraform',
           'zypper': 'terraform',
           'apk': 'terraform'}},
 {'key': 'consul',
  'cat': 'dev',
  'icon': '🚢',
  'name_en': 'Consul',
  'name_zh': 'Consul 服务发现',
  'desc_en': 'Service discovery mesh',
  'desc_zh': '服务发现与网格',
  'pkgs': {'apt': 'consul', 'dnf': 'consul', 'yum': 'consul', 'pacman': 'consul', 'zypper': 'consul', 'apk': 'consul'}},
 {'key': 'prometheus',
  'cat': 'database',
  'icon': '🔆',
  'name_en': 'Prometheus',
  'name_zh': 'Prometheus 监控',
  'desc_en': 'System monitoring',
  'desc_zh': '系统监控',
  'pkgs': {'apt': 'prometheus prometheus-node-exporter',
           'dnf': 'prometheus',
           'yum': 'prometheus',
           'pacman': 'prometheus',
           'zypper': 'prometheus',
           'apk': 'prometheus'}},
 {'key': 'grafana',
  'cat': 'database',
  'icon': '📊',
  'name_en': 'Grafana',
  'name_zh': 'Grafana 可视化',
  'desc_en': 'Monitoring dashboards',
  'desc_zh': '监控仪表盘',
  'pkgs': {'apt': 'grafana',
           'dnf': 'grafana',
           'yum': 'grafana',
           'pacman': 'grafana',
           'zypper': 'grafana',
           'apk': 'grafana'}},
 {'key': 'cockpit',
  'cat': 'system',
  'icon': '🚧',
  'name_en': 'Cockpit',
  'name_zh': 'Cockpit Web 管理',
  'desc_en': 'Web-based server management',
  'desc_zh': '基于 Web 的服务器管理',
  'pkgs': {'apt': 'cockpit',
           'dnf': 'cockpit',
           'yum': 'cockpit',
           'pacman': 'cockpit',
           'zypper': 'cockpit',
           'apk': 'cockpit'}},
 {'key': 'gitlab',
  'cat': 'web',
  'icon': '💚',
  'name_en': 'GitLab Runner',
  'name_zh': 'GitLab Runner CI',
  'desc_en': 'GitLab CI runner',
  'desc_zh': 'GitLab CI 执行器',
  'pkgs': {'apt': 'gitlab-runner',
           'dnf': 'gitlab-runner',
           'yum': 'gitlab-runner',
           'pacman': 'gitlab-runner',
           'zypper': 'gitlab-runner',
           'apk': 'gitlab-runner'}},
 {'key': 'jenkins',
  'cat': 'web',
  'icon': '🧵',
  'name_en': 'Jenkins',
  'name_zh': 'Jenkins CI',
  'desc_en': 'Continuous integration',
  'desc_zh': '持续集成服务器',
  'pkgs': {'apt': 'jenkins',
           'dnf': 'jenkins',
           'yum': 'jenkins',
           'pacman': 'jenkins',
           'zypper': 'jenkins',
           'apk': 'jenkins'}},
 {'key': 'plex',
  'cat': 'media',
  'icon': '🎭',
  'name_en': 'Plex',
  'name_zh': 'Plex 媒体服务器',
  'desc_en': 'Media streaming server',
  'desc_zh': '媒体流媒体服务器',
  'pkgs': {'apt': 'plexmediaserver',
           'dnf': 'plexmediaserver',
           'yum': 'plexmediaserver',
           'pacman': 'plex-media-server',
           'zypper': 'plexmediaserver',
           'apk': 'plexmediaserver'}},
 {'key': 'homeassistant',
  'cat': 'system',
  'icon': '🏠',
  'name_en': 'Home Assistant',
  'name_zh': 'Home Assistant 智能家居',
  'desc_en': 'Smart home hub',
  'desc_zh': '智能家居中枢',
  'pkgs': {'apt': 'homeassistant',
           'dnf': 'homeassistant',
           'yum': 'homeassistant',
           'pacman': 'home-assistant',
           'zypper': 'homeassistant',
           'apk': 'homeassistant'}},
 {'key': 'pihole',
  'cat': 'network',
  'icon': '🛡',
  'name_en': 'Pi-hole',
  'name_zh': 'Pi-hole 广告拦截',
  'desc_en': 'DNS-based ad blocker',
  'desc_zh': '基于 DNS 的广告拦截器',
  'pkgs': {'apt': 'pihole',
           'dnf': 'pihole',
           'yum': 'pihole',
           'pacman': 'pi-hole',
           'zypper': 'pihole',
           'apk': 'pihole'}},
 {'key': 'nagios',
  'cat': 'database',
  'icon': '❓',
  'name_en': 'Nagios',
  'name_zh': 'Nagios 监控',
  'desc_en': 'Monitoring and alerting',
  'desc_zh': '监控与告警',
  'pkgs': {'apt': 'nagios4',
           'dnf': 'nagios',
           'yum': 'nagios',
           'pacman': 'nagios',
           'zypper': 'nagios',
           'apk': 'nagios'}},
 {'key': 'sensu',
  'cat': 'database',
  'icon': '📌',
  'name_en': 'Sensu Go',
  'name_zh': 'Sensu Go 监控',
  'desc_en': 'Monitoring pipeline',
  'desc_zh': '监控流水线',
  'pkgs': {'apt': 'sensu-go-agent',
           'dnf': 'sensu-go-agent',
           'yum': 'sensu-go-agent',
           'pacman': 'sensu-go-agent',
           'zypper': 'sensu-go-agent',
           'apk': 'sensu-go-agent'}}]
def _pkg_name(info: SystemInfo, pkg: dict) -> str:
    """Return the install command string for a package given system info."""
    pm = info.package_manager
    if "custom" in pkg and pm in pkg["custom"]:
        return pkg["custom"][pm]
    target = pkg["pkgs"].get(pm, "")
    if not target:
        # fallback: try any
        target = next(iter(pkg["pkgs"].values()), "")
    if not target:
        name = pkg["name_en"]
        return f"echo 'Unsupported package manager for {name}'"
    return install_command(info, target)


class AppMarket(QWidget):
    """The app market panel with filterable package cards."""

    install_requested = pyqtSignal(str)  # emits the full command to run

    def __init__(self, system_info: SystemInfo, parent=None):
        super().__init__(parent)
        self.info = system_info
        self._current_cat = "all"
        self._build_ui()
        self._render_cards()

    def _build_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(8, 8, 8, 8)
        layout.setSpacing(8)

        # Header: system info + category filter
        header = QHBoxLayout()
        self.sys_label = QLabel()
        self.sys_label.setStyleSheet("color: #a6e3a1; font-weight: 600; font-size: 13px;")
        header.addWidget(self.sys_label)
        header.addStretch(1)

        self.cat_combo = QComboBox()
        self.cat_combo.addItem(tr("cat_all"), "all")
        self.cat_combo.addItem(tr("cat_dev"), "dev")
        self.cat_combo.addItem(tr("cat_web"), "web")
        self.cat_combo.addItem(tr("cat_database"), "database")
        self.cat_combo.addItem(tr("cat_system"), "system")
        self.cat_combo.addItem(tr("cat_network"), "network")
        self.cat_combo.addItem(tr("cat_security"), "security")
        self.cat_combo.addItem(tr("cat_media"), "media")
        self.cat_combo.currentIndexChanged.connect(self._on_cat_changed)
        header.addWidget(self.cat_combo)
        layout.addLayout(header)

        # Scrollable card area
        self.scroll = QScrollArea()
        self.scroll.setWidgetResizable(True)
        self.scroll.setFrameShape(QFrame.Shape.NoFrame)
        self.scroll_widget = QWidget()
        self.cards_layout = QGridLayout(self.scroll_widget)
        self.cards_layout.setSpacing(8)
        self.cards_layout.setContentsMargins(0, 0, 0, 0)
        self.scroll.setWidget(self.scroll_widget)
        layout.addWidget(self.scroll, 1)

        # Update system label
        self._update_sys_label()

    def _update_sys_label(self):
        if self.info and self.info.detected:
            self.sys_label.setText(f"🖥️  {self.info.summary()}")
        else:
            self.sys_label.setText(tr("market_detecting"))

    def _on_cat_changed(self):
        self._current_cat = self.cat_combo.currentData()
        self._render_cards()

    def _render_cards(self):
        # Clear existing cards
        while self.cards_layout.count():
            item = self.cards_layout.takeAt(0)
            w = item.widget()
            if w:
                w.deleteLater()

        lang = "zh"  # determined by i18n later; use current language
        from i18n import get_language
        lang = get_language()

        row, col = 0, 0
        for pkg in PACKAGES:
            if self._current_cat != "all" and pkg["cat"] != self._current_cat:
                continue
            pm = self.info.package_manager if self.info else "unknown"
            # Skip packages not available for this PM
            if pm not in pkg["pkgs"] and not ("custom" in pkg and pm in pkg.get("custom", {})):
                continue

            card = self._make_card(pkg, lang)
            self.cards_layout.addWidget(card, row, col)
            col += 1
            if col >= 2:
                col = 0
                row += 1

        if self.cards_layout.count() == 0:
            empty = QLabel(tr("market_no_packages"))
            empty.setStyleSheet("color: #6c7086; padding: 20px;")
            empty.setAlignment(Qt.AlignmentFlag.AlignCenter)
            self.cards_layout.addWidget(empty, 0, 0)

    def _make_card(self, pkg: dict, lang: str) -> QWidget:
        card = QFrame()
        card.setObjectName("AppCard")
        card.setStyleSheet(
            "QFrame#AppCard { background-color: #181825; border: 1px solid #313244;"
            " border-radius: 10px; }"
            "QFrame#AppCard:hover { border: 1px solid #89b4fa; }"
        )
        v = QVBoxLayout(card)
        v.setContentsMargins(12, 10, 12, 10)
        v.setSpacing(4)

        # Title row: icon + name
        title_row = QHBoxLayout()
        icon_lbl = QLabel(pkg["icon"])
        icon_lbl.setStyleSheet("font-size: 20px;")
        title_row.addWidget(icon_lbl)
        name = pkg["name_zh"] if lang == "zh" else pkg["name_en"]
        name_lbl = QLabel(name)
        name_lbl.setStyleSheet("font-weight: 600; color: #cdd6f4;")
        title_row.addWidget(name_lbl)
        title_row.addStretch(1)
        v.addLayout(title_row)

        # Description
        desc = pkg["desc_zh"] if lang == "zh" else pkg["desc_en"]
        desc_lbl = QLabel(desc)
        desc_lbl.setStyleSheet("color: #a6adc8; font-size: 12px;")
        desc_lbl.setWordWrap(True)
        v.addWidget(desc_lbl)

        # Install button
        btn = QPushButton(tr("market_install"))
        btn.setStyleSheet(
            "QPushButton { background-color: #40a02b; color: white; border: none;"
            " border-radius: 6px; padding: 6px; font-weight: 600; }"
            "QPushButton:hover { background-color: #54a83f; }"
            "QPushButton:pressed { background-color: #36871f; }"
        )
        btn.clicked.connect(lambda: self._install(pkg))
        v.addWidget(btn)

        return card

    def _install(self, pkg: dict):
        cmd = _pkg_name(self.info, pkg)
        self.install_requested.emit(cmd + "\r")

    def set_system_info(self, info: SystemInfo):
        self.info = info
        self._update_sys_label()
        self._render_cards()

    def retranslate_ui(self):
        # Update category combo labels
        self.cat_combo.setItemText(0, tr("cat_all"))
        self.cat_combo.setItemText(1, tr("cat_dev"))
        self.cat_combo.setItemText(2, tr("cat_web"))
        self.cat_combo.setItemText(3, tr("cat_database"))
        self.cat_combo.setItemText(4, tr("cat_system"))
        self.cat_combo.setItemText(5, tr("cat_network"))
        self.cat_combo.setItemText(6, tr("cat_security"))
        self.cat_combo.setItemText(7, tr("cat_media"))
        self._update_sys_label()
        self._render_cards()
